### ISSUE TITLE
Is wildcard in pattern supported (to remove every current label)?

### ISSUE THREAD

**Issue by damianobarbati** [jasonbellamy/git-label-cli#10]
```
$ git-label-cli remove -p '*' -t dfa3b1cdee334f647fd2f68f71b26f0d7e381f9a
TypeError: labels.map is not a function
    at deleteLabels (/Users/damiano/Desktop/react-simple-app/node_modules/git-label/dist/lib/label.js:143:29)
    at remove (/Users/damiano/Desktop/react-simple-app/node_modules/git-label/dist/index.js:47:34)
    at <anonymous>

```

**Comment by jasonbellamy** [comment]
@damianobarbati It's not currently but I'd be more then happy to accept a PR that adds that functionality.

**Comment by himynameisdave** [comment]
@damianobarbati another tool you can use (which is less simple but more comprehensive) to accomplish this from the command line is [`git-labelmaker`](https://github.com/himynameisdave/git-labelmaker#remove-labels). It's more of a prompt-based system though, so I'm not sure if it's quite what you're looking for.

**Comment by damianobarbati** [comment]
@jasonbellamy @himynameisdave thanks for replying so quickly :)

I'm creating my app-prototype to quickly set-up and run a project and I'd like to have (as I'm used to) a yarn command to fire like: `yarn labels` which 
- removes github default labels
- add labels defined in a given path

I already checked out *git-labelmaker* but I thought this one was better because not interactive.
The best was to:
```
$ git-label-cli remove -t <token> -p *
$ git-label-cli add -t <token> -p config/labels.json
# in my package.json scripts
"labels": "git-label-cli remove -t <token> -p * && git-label-cli add -t <token> -p config/labels.json"
```
Then after cloning my app prototype just firing `yarn labels` would sync labels, no 2nd step.
Is this possible?
