### ISSUE TITLE
Add usage examples to README

### ISSUE THREAD

**Issue by JamieMason** [jasonbellamy/git-label-cli#9]
Hey @jasonbellamy, thanks for creating this tool. 
I'm probably being dumb here, but could you add some usage examples? I've tried all kinds of different ways to try and figure it out on my own but, as you'll see below — I'm failing pretty hard.

```
jmason at wh0002279 in ~/Desktop
$ npm i -g git-label-cli
/usr/local/bin/git-label -> /usr/local/lib/node_modules/git-label-cli/dist/index.js
git-label-cli@3.0.0 /usr/local/lib/node_modules/git-label-cli
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── glob@6.0.4 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── inquirer@0.11.4 (ansi-regex@2.0.0, strip-ansi@3.0.1, ansi-escapes@1.1.1, figures@1.4.0, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, run-async@0.1.0, readline2@1.0.1, string-width@1.0.1, cli-cursor@1.0.2, chalk@1.1.1, lodash@3.10.1)
└── git-label@4.1.1 (lineder@0.1.1, request@2.69.0)

jmason at wh0002279 in ~/Desktop
$ git-label --repo JamieMason/temp-test

jmason at wh0002279 in ~/Desktop
$ git-label --repo JamieMason/temp-test --token << my api token here >>

jmason at wh0002279 in ~/Desktop
$ git-label --repo JamieMason/temp-test --token << my api token here >> add
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop
$ git-label --repo JamieMason/temp-test --token << my api token here >> add *
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop
$ git-label --repo JamieMason/temp-test --token << my api token here >> add '*'
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop
$ git-label --repo JamieMason/temp-test --token << my api token here >> remove default
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop
$ git-label --help

  Usage: git-label [options] [command]


  Commands:

    add      Add the specified labels to a repo
    remove   Remove the specified labels from a repo

  Options:

    -h, --help            output usage information
    -i, --interactive     run in interactive mode
    -a, --api <api>       api url
    -t, --token <token>   api token
    -r, --repo <repo>     repo name [username/repo]
    -p, --pattern <glob>  globbing pattern to the label packages


jmason at wh0002279 in ~/Desktop
$ git-label add --help

  Usage: add [options]

  Add the specified labels to a repo

  Options:

    -h, --help  output usage information


jmason at wh0002279 in ~/Desktop
$ git-label remove default --repo JamieMason/temp-test --token << my api token here >>
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop
$ git-label remove --repo JamieMason/temp-test --token << my api token here >> default
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop
$ mkdir test

jmason at wh0002279 in ~/Desktop
$ cd test

jmason at wh0002279 in ~/Desktop/test
$ git init
Initialized empty Git repository in /Users/jmason/Desktop/test/.git/

jmason at wh0002279 in ~/Desktop/test on master
$ git-label remove default --repo JamieMason/temp-test --token << my api token here >>
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop/test on master
$ git-label --repo JamieMason/temp-test --token << my api token here >> remove default
[TypeError: glob pattern string required]

jmason at wh0002279 in ~/Desktop/test on master
$ git-label remove --pattern default --repo JamieMason/temp-test --token << my api token here >>
[TypeError: Reduce of empty array with no initial value]

jmason at wh0002279 in ~/Desktop/test on master
$ git-label remove --pattern 'default' --repo 'JamieMason/temp-test' --token << my api token here >>
[TypeError: Reduce of empty array with no initial value]

jmason at wh0002279 in ~/Desktop/test on master
$ git-label remove --pattern 'bug' --repo 'JamieMason/temp-test' --token << my api token here >>
[TypeError: Reduce of empty array with no initial value]

jmason at wh0002279 in ~/Desktop/test on master
$ git-label remove -i --repo 'JamieMason/temp-test' --token << my api token here >>
? api url https://api.github.com


/usr/local/lib/node_modules/git-label-cli/dist/lib/repo.js:25
      resolve(/(:)(.+)(\.git)/g.exec(res)[2].split('/').filter(function (key, index, xs) {
                                         ^

TypeError: Cannot read property '2' of null
    at /usr/local/lib/node_modules/git-label-cli/dist/lib/repo.js:25:42
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

jmason at wh0002279 in ~/Desktop/test on master
$ git-label remove -i
? api url https://api.github.com


/usr/local/lib/node_modules/git-label-cli/dist/lib/repo.js:25
      resolve(/(:)(.+)(\.git)/g.exec(res)[2].split('/').filter(function (key, index, xs) {
                                         ^

TypeError: Cannot read property '2' of null
    at /usr/local/lib/node_modules/git-label-cli/dist/lib/repo.js:25:42
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by JamieMason** [comment]
I've got a little further, I've learned you have to be in a checkout of the project rather than anywhere on your file system (I'd wrongly assumed you can manage your GitHub repos using only the CLI options).

But I'm still facing errors;

```
jmason at wh0002279 in ~/Desktop/test on master
$ git clone https://github.com/JamieMason/temp-test.git
Cloning into 'temp-test'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.

jmason at wh0002279 in ~/Desktop/test on master
$ cd temp-test/

jmason at wh0002279 in ~/Desktop/test/temp-test on master
$ git-label -i remove
? api url https://api.github.com
? repo name [username/repo] JamieMason/temp-test
? api token << my api token here >>
? globbing pattern to the label packages default
[TypeError: Reduce of empty array with no initial value]

jmason at wh0002279 in ~/Desktop/test/temp-test on master
$ git-label -i remove
? api url https://api.github.com
? repo name [username/repo] JamieMason/temp-test
? api token << my api token here >>
? globbing pattern to the label packages 'bug'
[TypeError: Reduce of empty array with no initial value]

jmason at wh0002279 in ~/Desktop/test/temp-test on master
$ git-label -i remove
? api url https://api.github.com
? repo name [username/repo] JamieMason/temp-test
? api token << my api token here >>
? globbing pattern to the label packages *
[TypeError: Reduce of empty array with no initial value]
```

Thanks for your time.

**Comment by JamieMason** [comment]
Hey @jasonbellamy – just checking if this project is still active?

**Comment by jasonbellamy** [comment]
@JamieMason this project is still alive and in daily use today. Are you still having issues getting it running?

**Comment by JamieMason** [comment]
Thanks @jasonbellamy, I couldn't get it to work unfortunately – I've since found https://github.com/IonicaBizau/github-labeller though which is working ok.

**Comment by jasonbellamy** [comment]
Okay great, I'm glad you've found something that is working well for you. 

I'll make an effort to make the documentation clearer in the future. 

Thanks for taking the time to comment. 
- Jason

**Comment by JamieMason** [comment]
You're welcome, this looks a great project but I just ran into some issues or misread how it's meant to be used.

Thanks.
